version: "3"
services:
  dns:
    restart: always
    image: quay.io/ftrivino/ci-dns:latest
    container_name: dns
    volumes:
      - ./data/config/dnsmasq.conf:/etc/dnsmasq.conf
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - SYS_CHROOT
    security_opt:
      - apparmor=unconfined
      - label=disable
      - seccomp=unconfined
    networks:
      sssd:
        ipv4_address: 172.16.100.2
  ipa:
    image: quay.io/sssd/ci-ipa:latest
    container_name: ipa
    hostname: master.ipa.test
    dns: 172.16.100.2
    volumes:
      - ./shared:/shared:rw
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
      - AUDIT_WRITE
      - AUDIT_CONTROL
      - SYS_CHROOT
      - NET_ADMIN
    security_opt:
      - apparmor=unconfined
      - label=disable
      - seccomp=unconfined
    networks:
      sssd:
        ipv4_address: 172.16.100.10
    depends_on:
      dns:
        condition: service_completed_successfully
        restart: true
  bridge:
    image: quay.io/ftrivino/ipatuura-prod
    container_name: bridge
    hostname: bridge.ipa.test
    environment:
      - DJANGO_SECRET_KEY="^$z^y$^ndlem@_f1)($_5vye6t!dk#8+8&9=y5*=-r(v465xg+"
      - DJANGO_DEBUG='False'
    networks:
      sssd:
        ipv4_address: 172.16.100.100
    depends_on:
      ipa:
        condition: service_completed_successfully
        restart: true
  keycloak:
    image: quay.io/ftrivino/ci-keycloak
    container_name: keycloak
    hostname: master.keycloak.test
    dns: 172.16.100.2
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
      - AUDIT_WRITE
      - AUDIT_CONTROL
      - NET_ADMIN
      - SYS_CHROOT
    security_opt:
      - apparmor=unconfined
      - label=disable
      - seccomp=unconfined
    networks:
      sssd:
        ipv4_address: 172.16.100.70
    depends_on:
      ipa:
        condition: service_completed_successfully
        restart: true
networks:
  sssd:
    name: sssd-ci
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.100.0/24
          gateway: 172.16.100.1
      options:
        driver: host-local
